// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBx5Hu9ea7LZ2TUe3xazNa4xyM8j423M',
    appId: '1:602308492916:web:480e00f6f78383d56d9b21',
    messagingSenderId: '602308492916',
    projectId: 'gaming-shop-ui',
    authDomain: 'gaming-shop-ui.firebaseapp.com',
    storageBucket: 'gaming-shop-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDztVRznrMhV6Vt-Un7YHOP3EzZoM-zONc',
    appId: '1:602308492916:android:7489cae5dae3ff8d6d9b21',
    messagingSenderId: '602308492916',
    projectId: 'gaming-shop-ui',
    storageBucket: 'gaming-shop-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmT4bVY_o6O-_zG9iO61Az5nxXMfg8Ul0',
    appId: '1:602308492916:ios:6ffbfb83b91bbb8b6d9b21',
    messagingSenderId: '602308492916',
    projectId: 'gaming-shop-ui',
    storageBucket: 'gaming-shop-ui.appspot.com',
    iosBundleId: 'com.patryklaskowski.gamingShopUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmT4bVY_o6O-_zG9iO61Az5nxXMfg8Ul0',
    appId: '1:602308492916:ios:d5450f2ad62614d96d9b21',
    messagingSenderId: '602308492916',
    projectId: 'gaming-shop-ui',
    storageBucket: 'gaming-shop-ui.appspot.com',
    iosBundleId: 'com.patryklaskowski.gamingShopUi.RunnerTests',
  );
}
